apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: default
spec:
  selector:
    app: myweather
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32434
  type: LoadBalancer
  
